spring:
  cloud:
    gateway:
      routes:
        - id: multiplications
          uri: lb://multiplication
          predicates:
            - Path=/api/multiplications/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: results
          uri: lb://multiplication
          predicates:
            - Path=/api/results/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: leaders
          uri: lb://gamification
          predicates:
            - Path=/api/leaders/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: stats
          uri: lb://gamification
          predicates:
            - Path=/api/stats/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
