
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RewritePath=/(?<base>.*?)/(?<segment>.*)/fgdfggd, /$\{segment}
      routes:
        - id: multiplication
          uri: http://localhost:8080/results
          predicates:
            - Path=/api/results/**
