spring:
  cloud:
    gateway:
      routes:
        - id: multiplications
          uri: http://localhost:8080/multiplications/
          predicates:
            - Path=/api/multiplications/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: results
          uri: http://localhost:8080/results/
          predicates:
            - Path=/api/results/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: leaders
          uri: http://localhost:8081/leaders/
          predicates:
            - Path=/api/leaders/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: stats
          uri: http://localhost:8081/stats/
          predicates:
            - Path=/api/stats/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
